version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR started on `date`
      - aws --version
      - echo Logging into Amazon ECR....
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 533267204385.dkr.ecr.us-west-1.amazonaws.com
      - echo setting repository URI....
      - REPOSITORY_URI=533267204385.dkr.ecr.us-west-1.amazonaws.com/cicdpipeline
      - echo setting image tag....
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo building and tagging started image on `date`
      - echo running mvn clean install....
      - mvn clean install
      - echo building docker image....
      - docker build -t $REPOSITORY_URI:latest .  # Use 'latest' as the Docker tag
      - echo tagging docker image....
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo pushing docker image to ECR started on `date`
      - echo pushing  image to repository....
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo setting container name....
      - DOCKER_CONTAINER_NAME=cicdpipeline
      - echo writing image definitions file....
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing image definitions file...
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json